version: '3'

services:
  web:
    build:
        context: ..
        args:
            - UID:1000
            - GID:1000
        dockerfile: docker/Dockerfile
    container_name: ydlapi
    restart: unless-stopped
    volumes:
        - ./data/:/opt/ydl_api/downloads/videos
        - ./logs/:/opt/ydl_api/logs
    ports:
        - 5012:5011
